### ISSUE TITLE
BinaryTree.java not working

### ISSUE THREAD

**Issue by janacm** [williamlin59/BinaryTree#1]
Hi,

When I run BinaryTree.java, it asks me for 5 letters, which I inputted, but then the output in the console is just lines and 0's. I am running this in Eclipse on Java 7

**Comment by williamlin59** [comment]
Hi
you can't run BinaryTree.java since it's only an interface.. The treetester is the java file which is runnable for testing the entire binary tree

**Comment by janacm** [comment]
Oops, I was actually looking at another github repo's BinaryTree.java which had the issue. My apologies.
